config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
root "pins#index"
get "about" => "pages#about"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ActiveRecord::Base
    belongs_to :user
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

    validates :image, presence: true
    validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
   devise_parameter_sanitizer.permit(:account_update, keys: [:name])
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
   @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
 <footer class="mbr-small-footer mbr-section mbr-section-nopadding" id="footer1-2" style="background-color: rgb(255, 255, 255); padding-top: 1.75rem; padding-bottom: 1.75rem;">
        
    <div class="container">
        <p class="text-xs-center">Copyright (c) 2017 Pinteresting.</p>
    </div>
</footer>

app/views/layouts/_header.html.erb
<section id="menu-0">

    <nav class="navbar navbar-dropdown bg-color transparent navbar-fixed-top">
        <div class="container">

            <div class="mbr-table">
                <div class="mbr-table-cell">

                    <div class="navbar-brand">
                        <a href="/" class="mbr-iconfont mbr-iconfont-menu navbar-logo" style="color: rgb(0, 0, 0);"><i class="fa fa-camera" aria-hidden="true"></i></a>
                        <%= link_to "Pinteresting", root_path, class: "navbar-caption text-primary" %>
                    </div>

                </div>
                <div class="mbr-table-cell">

                    <button class="navbar-toggler pull-xs-right hidden-md-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
                        <div class="hamburger-icon"></div>
                    </button>

                    <ul class="nav-dropdown nav-btn-right collapse pull-xs-right nav navbar-nav navbar-toggleable-sm" id="exCollapsingNavbar">
                        <li class="nav-item dropdown">
                            <%= link_to "Home", root_path, class: "mbr-iconfont mbr-iconfont-btn", style: "color: black;" %>
                        </li>
                        <li class="nav-item dropdown">
                            <%= link_to new_pin_path, class: "mbr-iconfont mbr-iconfont-btn", style: "color: #b8312f;" do %>
                                <i class="fa fa-plus" aria-hidden="true"></i> New Pin
                            <% end %>
                        </li>
                        <% if user_signed_in? %>
                            <li class="nav-item nav-btn">
                                <%= link_to "Account Settings", edit_user_registration_path, class: "nav-link btn btn-primary-outline btn-primary" %>
                            </li>
                            <li class="nav-item nav-btn">
                                <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link btn btn-primary-outline btn-primary" %>
                            </li> 
                        <% else %>        
                            <li class="nav-item nav-btn">
                                <%= link_to "Sign In!", new_user_session_path, class: "nav-link btn btn-primary-outline btn-primary" %>
                            </li> 
                        <% end %>
                    </ul>
                    <button hidden="" class="navbar-toggler navbar-close" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
                        <div class="close-icon"></div>
                    </button>

                </div>
            </div>

        </div>
    </nav>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <%= render 'layouts/header' %>
    
    <%= yield %>

    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/layouts/login.html.erb
<!-- HEADER -->

<nav class="navbar navbar-static-top navbar-default" role="navigation">
<div class="container">
<!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Pinteresting", root_path, class: "navbar-brand", style: "font-size: 1.6em;" %>
    </div>

  <!-- Collect the nav links, forms, and other content for toggling -->

    <div class="collapse navbar-collapse navbar-ex1-collapse"> 
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> New Pin
            <% end %>
        </li>
        <li><%= link_to "About", about_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In!", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>


<!-- BODY -->

<div class="jumbotron center">
  <h1>Welcome to my app!</h1>
  <p>
    <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  </p>

</div>

app/views/pages/_home.html.erb
<section class="mbr-section mbr-section-hero mbr-section-full header2 mbr-parallax-background mbr-after-navbar mbr-bg-image" id="header2-3">

    <div class="mbr-overlay" style="opacity: 0.3; background-color: rgb(0, 0, 0);">
    </div>

    <div class="mbr-table mbr-table-full">
        <div class="mbr-table-cell">

            <div class="container">
                <div class="mbr-section row">
                    <div class="mbr-table-md-up">

                        <div class="mbr-table-cell col-md-5 content-size text-xs-center text-md-right">

                            <h3 class="mbr-section-title display-2">Welcome!</h3>

                            <div class="mbr-section-text">
                                <p>A collection of ideas in pictures. Start sharing your pins with the world and see what your friends are posting!</p>
                            </div>

                            <div class="mbr-section-btn">
                              <%= link_to "SIGN IN", new_user_session_path, class: "btn btn-white" %>
                              <%= link_to "SIGN UP!", new_user_registration_path, class: "btn btn-primary" %>
                            </div>

                        </div>
                        <div class="mbr-table-cell mbr-valign-top mbr-left-padding-md-up col-md-7 image-size" style="width: 50%;">
                            <div class="mbr-figure"><%= image_tag('pin.jpg') %></div>
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="mbr-arrow mbr-arrow-floating hidden-sm-down" aria-hidden="true"><a href="#next"><i class="mbr-arrow-icon"></i></a></div>

</section>

app/views/pages/home.html.erb
<section class="mbr-section mbr-section-hero mbr-section-full header2 mbr-parallax-background mbr-after-navbar mbr-bg-image" id="header2-3">

    <div class="mbr-overlay" style="opacity: 0.3; background-color: rgb(0, 0, 0);">
    </div>

    <div class="mbr-table mbr-table-full">
        <div class="mbr-table-cell">

            <div class="container">
                <div class="mbr-section row">
                    <div class="mbr-table-md-up">

                        <div class="mbr-table-cell col-md-5 content-size text-xs-center text-md-right">

                            <h3 class="mbr-section-title display-2">Welcome!</h3>

                            <div class="mbr-section-text">
                                <p>A collection of ideas in pictures. Start sharing your pins with the world and see what your friends are posting!</p>
                            </div>

                            <div class="mbr-section-btn"><a class="btn btn-white" href="https://mobirise.com">SIGN IN</a> <a class="btn btn-primary" href="https://mobirise.com">SIGN UP!</a></div>

                        </div>
                        <div class="mbr-table-cell mbr-valign-top mbr-left-padding-md-up col-md-7 image-size" style="width: 50%;">
                            <div class="mbr-figure"><%= image_tag('pin.jpg') %></div>
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="mbr-arrow mbr-arrow-floating hidden-sm-down" aria-hidden="true"><a href="#next"><i class="mbr-arrow-icon"></i></a></div>

</section>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image, style: "padding-top: 20px;" %>
    <p><%= f.file_field :image %></p>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<section class="mbr-section mbr-section-hero mbr-section-full header2 mbr-parallax-background mbr-after-navbar mbr-bg-image" id="header2-3">
    <div class="mbr-overlay" style="opacity: 0.3; background-color: rgb(0, 0, 0);">
    </div>

      <div class="mbr-table mbr-table-full">
        <div class="mbr-table-cell">      
          <div class="container container-signup">
            <div class="mbr-section mbr-signup">
                    <div class="panel panel-default">
                      <div class="panel-heading">
                        <div class="panel-title">
                          <h1>Edit Pin!</h1>
                        </div>
                      </div>

                      <%= render 'form', pin: @pin %>

                      <%= link_to 'Show', @pin %> |
                      <%= link_to 'Back', pins_path %>

                    </div> 
            </div> 
          </div> 
        </div> 
      </div> 
</section>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<section class="mbr-section mbr-section-hero mbr-section-full header2 mbr-parallax-background mbr-after-navbar mbr-bg-image" id="header2-3">

    <div class="mbr-overlay" style="opacity: 0.3; background-color: rgb(0, 0, 0);">
    </div>
    
      
           <div class="mbr-section">
              
         
                <div class="container"> 

                  <div class="card">   
                    <div class="card-block">
                
                      
                          <div id="pins" class="transitions-enabled">
                            <% @pins.each do |pin| %>
                              <div class="box panel panel-default">
                                <img class: "card-img-top img-fluid"><%= link_to image_tag(pin.image.url(:medium)), pin %>
                                <div class="panel-body">
                                  <p><%= pin.description %></p>
                                  <p><strong><%= pin.user.name if pin.user %></strong></p>
                                  
                                  <% if current_user && pin.user == current_user %>
                                    <div class="actions">
                                      <%= link_to edit_pin_path(pin) do %>
                                       <span class="glyphicon glyphicon-edit"></span>
                                        Edit
                                      <% end %>
                                      <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
                                        <span class="glyphicon glyphicon-trash"></span>
                                        Delete
                                      <% end %>
                                    </div>
                                  <% end %>
                                </div>
                              </div>
                            <% end %>
                          </div>    
                                       

                      <div class="mbr-section">
                         <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
                      </div>
              
                    </div>
                  </div>
                </div>
              
          </div> 

      
        
</section>

app/views/pins/new.html.erb
<section class="mbr-section mbr-section-hero mbr-section-full header2 mbr-parallax-background mbr-after-navbar mbr-bg-image" id="header2-3">
    <div class="mbr-overlay" style="opacity: 0.3; background-color: rgb(0, 0, 0);">
    </div>

      <div class="mbr-table mbr-table-full">
        <div class="mbr-table-cell">      
          <div class="container container-signup">
            <div class="mbr-section mbr-signup">
                    <div class="panel panel-default">
                      <div class="panel-heading">
                        <div class="panel-title">
                          <h1>Create Your Pin!</h1>
                        </div>
                      </div>

                      <%= render 'form' %>

                    </div> 
            </div> 
          </div> 
        </div> 
      </div> 
</section>

app/views/pins/show.html.erb
<section class="mbr-section mbr-section-hero mbr-section-full header2 mbr-parallax-background mbr-after-navbar mbr-bg-image" id="header2-3">
    <div class="mbr-overlay" style="opacity: 0.3; background-color: rgb(0, 0, 0);">
    </div>

      <div class="mbr-table mbr-table-full">
        <div class="mbr-table-cell">  
          <div class="container">

            <%= link_to pins_path, style: "color: black;" do %>
              <i class="fa fa-chevron-left" aria-hidden="true"></i>
              Back
            <% end %>

            
              <div class="card card-inverse" style="width: 340px; position: relative; background-color: #333; border-color: #333;">
                <div class="card-block">
                  <div class="box">
                      
                        
                          <div class="panel-heading center">
                            <%= image_tag @pin.image.url(:medium) %>
                          </div>
                          <div class="panel-body">
                          <p><%= @pin.description %></p>
                          <p><strong><%= @pin.user.name if @pin.user %></strong></p>

                          <% if current_user && @pin.user == current_user %>
                            <%= link_to edit_pin_path(@pin), style: "color: black;" do %>
                              <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                              Edit
                            <% end %>
                          <% end %>
                          </div>
                  </div>  
                </div>    
              </div>      
                  

          </div>
        </div> 
      </div> 
</section>